import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * Deterministic local fallback summary generator.
 * Used when the LLM is unavailable — keeps the product fully functional.
 */
export function buildFallbackSummary(evidence: Record<string, unknown>): {
  sections: {
    executiveSummary: string;
    technicalAnalysis: string;
    whyThisMatters: string;
    recommendedInvestigation: string[];
    suggestedContainment: string[];
    confidenceCaveats: string;
  };
  source: "fallback";
} {
  const inc = evidence as {
    incidentId?: string;
    title?: string;
    category?: string;
    severity?: string;
    riskScore?: number;
    alertCount?: number;
    eventCount?: number;
    entities?: string[];
    meanConfidence?: number;
    meanAnomaly?: number;
    peakAnomaly?: number;
    categoryMix?: Record<string, number>;
    firstSeen?: number;
    lastSeen?: number;
    topContributors?: { feature: string; contribution: number }[];
    containmentPlaybook?: string[];
    sampleEvents?: { category: string; attackProbability: number; anomalyScore: number }[];
    groundTruthMix?: Record<string, number>;
  };

  const cat = inc.category ?? "unknown";
  const sev = inc.severity ?? "Unknown";
  const risk = (inc.riskScore ?? 0).toFixed(0);
  const n = inc.alertCount ?? inc.eventCount ?? 0;
  const mix = Object.entries(inc.categoryMix ?? {})
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([c, k]) => `${c} (${k})`)
    .join(", ");
  const topFeat = (inc.topContributors ?? []).slice(0, 4).map((t) => t.feature).join(", ");
  const dur = ((inc.lastSeen ?? 0) - (inc.firstSeen ?? 0)) / 1000;

  const exec =
    `Incident ${inc.incidentId ?? ""} is a ${sev.toLowerCase()}-severity ${cat} campaign ` +
    `consolidating ${n} correlated alerts into one prioritized case (risk ${risk}/100). ` +
    `Correlated attack behavior spans ${dur.toFixed(0)}s of replay time across ${inc.entities?.length ?? 1} simulated pseudo-entities.`;

  const tech =
    `The detection engine classified the dominant behavior as ${cat}` +
    (mix ? ` (mix: ${mix})` : "") +
    ` with mean model confidence of ${((inc.meanConfidence ?? 0) * 100).toFixed(0)}% and mean anomaly score ` +
    `${(inc.meanAnomaly ?? 0).toFixed(0)}/100 (peak ${(inc.peakAnomaly ?? 0).toFixed(0)}/100). ` +
    (topFeat ? `The strongest model evidence comes from: ${topFeat}. ` : "") +
    `Alert correlation used predicted-category similarity, temporal proximity, and behavioral distance; ` +
    `pseudo-entity labels are SIMULATED metadata (the dataset contains no IP/user fields).`;

  const why =
    `${cat} activity at ${sev.toLowerCase()} severity can indicate an active campaign rather than isolated noise. ` +
    `With risk ${risk}/100 the recommended posture is immediate triage: verify whether the correlated flows ` +
    `represent a real attack stage progression and whether targeted services are exposed.`;

  const investigate = [
    `Review the ${Math.min(10, n)} highest-risk events in the incident evidence tab and confirm the model's reasoning`,
    `Compare flow characteristics against baseline traffic for the implicated services (proto/service/state distribution)`,
    `Check whether anomaly scores escalate over the incident window (indicates sustained, not transient, behavior)`,
    `Correlate with the attack-story timeline to identify category transitions (possible multi-stage campaign)`,
  ];

  const contain = inc.containmentPlaybook?.length
    ? inc.containmentPlaybook
    : ["Apply standard triage for this attack category", "Monitor for recurrence within the correlation window"];

  const caveats =
    `This summary was generated by the deterministic fallback (LLM unavailable). Predictions come from models trained ` +
    `on UNSW-NB15 flow features only: no source/destination IPs, users, devices, or true timestamps exist in the supplied data. ` +
    `Timestamps and entity labels shown anywhere in this product are simulated replay metadata. ` +
    `Model probabilities are calibrated (Platt/temperature) but uncertainty remains, especially for rare classes (Worms, Shellcode).`;

  return {
    source: "fallback",
    sections: {
      executiveSummary: exec,
      technicalAnalysis: tech,
      whyThisMatters: why,
      recommendedInvestigation: investigate,
      suggestedContainment: contain,
      confidenceCaveats: caveats,
    },
  };
}

function buildEvidencePrompt(evidence: Record<string, unknown>): string {
  const inc = evidence as Parameters<typeof buildFallbackSummary>[0] & {
    status?: string;
    riskTrajectory?: { t: number; risk: number; count: number }[];
    story?: { title: string; detail: string; epistemics: string }[];
    sampleEvents?: { category: string; attackProbability: number; anomalyScore: number; riskScore?: number; topPositive?: { feature: string; contribution: number }[] }[];
  };
  const slim = {
    incidentId: inc.incidentId,
    title: inc.title,
    category: inc.category,
    severity: inc.severity,
    status: inc.status,
    riskScore: inc.riskScore,
    alertCount: inc.alertCount,
    eventCount: inc.eventCount,
    entities: inc.entities,
    meanConfidence: inc.meanConfidence,
    meanAnomaly: inc.meanAnomaly,
    peakAnomaly: inc.peakAnomaly,
    categoryMix: inc.categoryMix,
    riskTrajectory: (inc.riskTrajectory ?? []).slice(-8),
    topContributors: inc.topContributors,
    story: (inc.story ?? []).map((s: { title: string; detail: string; epistemics: string }) => ({
      title: s.title, detail: s.detail, epistemics: s.epistemics,
    })),
    sampleEvents: (inc.sampleEvents ?? []).slice(0, 5).map((e) => ({
      category: e.category,
      attackProbability: e.attackProbability,
      anomalyScore: e.anomalyScore,
      riskScore: e.riskScore,
      topPositiveFeatures: e.topPositive?.slice(0, 3),
    })),
    groundTruthMix: inc.groundTruthMix,
  };
  return JSON.stringify(slim, null, 2);
}

const SYSTEM_PROMPT = `You are the CipherMind Sentinel AI Analyst — an incident-summary assistant for a Security Operations Center.
You receive structured EVIDENCE from a network-intrusion-detection system trained on the UNSW-NB15 dataset (network flow records: protocol, service, state, packet/byte counts, rates, TTLs, loads, jitter, TCP timing, connection-count features).

STRICT RULES (violations make the output useless):
1. Use ONLY the facts present in the evidence JSON. Never invent IPs, hostnames, users, malware families, CVEs, file hashes, or geolocation — the dataset contains none of these.
2. The evidence may include "entities" — these are SIMULATED pseudo-entities derived from flow features, not real devices. Refer to them as such.
3. Event timestamps are SIMULATED replay offsets in milliseconds, not real capture times.
4. Distinguish observed facts (model outputs, scores, counts) from inference (your interpretation). Use hedged language for the latter ("appears to", "is consistent with").
5. If the evidence includes "groundTruthMix", note it is shown only for demo-transparency evaluation, not something the model saw.
6. Recommendations must be safe, concrete analyst checks framed as suggestions, not confirmed truth.

Respond with STRICT JSON only (no markdown fences, no extra text) with exactly these keys:
{
  "executiveSummary": "1-3 sentences, plain language, what is happening and how serious",
  "technicalAnalysis": "1 paragraph: what the model saw — categories, confidence, anomaly, risk, key contributing features",
  "whyThisMatters": "2-4 sentences of security/business impact for a SOC manager",
  "recommendedInvestigation": ["4-6 concrete analyst checks grounded in the evidence"],
  "suggestedContainment": ["2-4 containment considerations framed as recommended actions"],
  "confidenceCaveats": "explicit limitations: simulated metadata, no IP/user fields, calibration, rare-class uncertainty"
}`;

export async function POST(request: Request) {
  let evidence: Record<string, unknown>;
  try {
    const body = (await request.json()) as { evidence?: Record<string, unknown> };
    evidence = body.evidence ?? (body as Record<string, unknown>);
    if (!evidence || typeof evidence !== "object") {
      return NextResponse.json({ error: "missing evidence" }, { status: 400 });
    }
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }

  const fallback = buildFallbackSummary(evidence);

  try {
    const { default: ZAI } = await import("z-ai-web-dev-sdk");
    const zai = await ZAI.create();
    const completion = await zai.chat.completions.create({
      messages: [
        { role: "assistant", content: SYSTEM_PROMPT },
        { role: "user", content: `Summarize this incident for the on-duty SOC analyst. EVIDENCE:\n${buildEvidencePrompt(evidence)}` },
      ],
      thinking: { type: "disabled" },
    });
    const content = completion.choices[0]?.message?.content;
    if (!content) throw new Error("empty LLM response");
    const cleaned = content.replace(/```json|```/g, "").trim();
    const parsed = JSON.parse(cleaned) as typeof fallback.sections;
    const required = ["executiveSummary", "technicalAnalysis", "whyThisMatters", "recommendedInvestigation", "suggestedContainment", "confidenceCaveats"];
    const missing = required.filter((k) => !(k in parsed));
    if (missing.length) throw new Error(`LLM response missing keys: ${missing.join(", ")}`);
    return NextResponse.json({ source: "llm", sections: parsed });
  } catch (e) {
    console.error("[ai/incident-summary] LLM failed, using deterministic fallback:", (e as Error).message);
    return NextResponse.json(fallback);
  }
}
